### ISSUE TITLE
PodioLegacyDataSvc vs PodioDataSvc?

### ISSUE THREAD

**Issue by ebrondol** [key4hep/k4Clue#45]
Running locally I noticed that the code is broken since [PR#42](https://github.com/key4hep/k4Clue/pull/42).
```
In file included from /afs/cern.ch/user/e/ebrondol/work/clue/k4Clue/src/ClueGaudiAlgorithmWrapper.cpp:1:
/afs/cern.ch/user/e/ebrondol/work/clue/k4Clue/src/ClueGaudiAlgorithmWrapper.h:52:3: error: 'PodioLegacyDataSvc' does not name a type; did you mean 'PodioDataSvc'?
   52 |   PodioLegacyDataSvc* m_podioDataSvc;
      |   ^~~~~~~~~~~~~~~~~~
      |   PodioDataSvc
```

Unfortunately, the CI was not running for the past 4 weeks and thus, the problem was not spotted before.

**Comment by tmadlener** [comment]
Is the CI running against the nightlies or against the release? Because for the nightlies the `PodioLegacyDataSvc` should be available.

Having had a brief look at the code, it also looks like the DataSvc is mainly needed to get at the CellIDEncoding, which could also be done via the newly introduced `MetaDataHandle`, so no need to explicitly have any DataSvc in the code any longer.

**Comment by tmadlener** [comment]
Yes, the "related reason" is key4hep/k4FWCore#100 ;)

There is a minimal example in the tests of k4FWCore (in both cases highlighting where the `MetaDataHandle` is used for getting data from or or putting data in it, there is a bit of setup necessary, but it should be somewhat straight forward to get that from the examples):
- reading: https://github.com/key4hep/k4FWCore/blob/master/test/k4FWCoreTest/src/components/k4FWCoreTest_cellID_reader.cpp#L25
- writing: https://github.com/key4hep/k4FWCore/blob/master/test/k4FWCoreTest/src/components/k4FWCoreTest_cellID_writer.cpp#L17

**Comment by ebrondol** [comment]
Update: 

- `MetaDataHandle` is currently available only for the nightlies
- I have tested locally switching to `MetaDataHandle`, but the input file used to test it does not contain `podio_metadata`
- I have followed the [official recipe](https://key4hep.github.io/key4hep-doc/k4marlinwrapper/doc/starterkit/k4MarlinWrapperCLIC/Readme.html), using the nightlies, to produce the new sample, but the reconstruction with input edm4hep files is not working due to
```
ToolSvc             ERROR Error initializing tool 'ToolSvc.Lcio2EDM4hep'
Output_REC          ERROR Failing initializing ToolHandles : Output_REC      Failed to retrieve tool Lcio2EDM4hepTool/Lcio2EDM4hep     StatusCode=FAILURE
EventLoopMgr        ERROR Unable to initialize Algorithm: Output_REC
```
@tmadlener suggested to wait for https://github.com/key4hep/k4MarlinWrapper/pull/120 to be finalized and it should solve the issue.
