### ISSUE TITLE
Include GPU machine in CI testing

### ISSUE THREAD

**Issue by ebrondol** [key4hep/k4Clue#8]

**Comment by vvolkl** [comment]
We can use the cern gitlab shared runners for this: https://gitlab.cern.ch/gitlabci-examples/gpu-tpu-arm-public-clouds

**Comment by fdplacido** [comment]
I tested yesterday on a RTX 8000 and it seems to run fine, see https://github.com/key4hep/k4Clue/pull/9. But if we CI this that would be awesome.

**Comment by ebrondol** [comment]
I am testing it today and validating #9 as well.

**Comment by ebrondol** [comment]
I am done with the tests and for me the PR is ready to go. We can keep this issue in relation with inserting GPU machine in future a CI. I will just modify the title accordingly.

**Comment by vvolkl** [comment]
This should be finally available: I've set up one of the FCC GPU machines as a dedicated gitlab runner, and mirrored this repository to https://gitlab.cern.ch/key4hep/k4Clue/ to make use of it. To see how it looks, hover on the commit status here: https://github.com/key4hep/k4Clue/pull/32

I'm not sure if the pipeline will also be triggered when PRs are opened by someone not in the key4hep organization, but we can live with that, I think.

**Comment by vvolkl** [comment]
Actually, I think the gitlab pipeline is only triggered when the PR is opened from a branch on the key4hep/k4clue repository. Triggering gitlab from pull requests from forks seems way more involved and is usually done via a bot.

It should be ok for the current contributors to just push an external branch to key4hep/k4clue though.

**Comment by ebrondol** [comment]
Hi @vvolkl thanks for this. So the 5 checks in #33 instead of 2 corresponds to the fact that two are triggered in github and two in gitlab w/GPU?

**Comment by vvolkl** [comment]
Hi @ebrondol, four of them are github actions workflows - two of them got triggered by the PR, two of them on the push when I pushed the same branch to key4hep/k4clue, and once the branch is in k4clue, the job on gitlab w/GPU is triggered.
